name_classID = {
    0: "None",
    1: "Warrior",
    2: "Paladin",
    3: "Hunter",
    4: "Rogue",
    5: "Priest",
    6: "Death Knight",
    7: "Shaman",
    8: "Mage",
    9: "Warlock",
    10: "Monk",
    11: "Druid",
    12: "Demon Hunter",
}

small_image_classID = {
    0: "icon_full",
    1: "class_warrior",
    2: "class_paladin",
    3: "class_hunter",
    4: "class_rogue",
    5: "class_priest",
    6: "class_deathknight",
    7: "class_shaman",
    8: "class_mage",
    9: "class_warlock",
    10: "class_monk",
    11: "class_druid",
    12: "class_demonhunter",
}

large_image_mapID = {
    # cities
    301: "city_stormwind",
    321: "city_orgrimmar",
    341: "city_ironforge",
    362: "city_thunderbluff",
    381: "city_darnassus",
    382: "city_undercity",
    471: "city_exodar",
    480: "city_silvermoon",
    481: "city_shattrath",
    504: "city_dalaran",
    903: "city_shrineoftwomoons",
    905: "city_shrineofsevenstars",
    971: "garrison_alliance",
    976: "garrison_horde",
    1009: "city_stormshield",
    1011: "city_warspear",
    1014: "city_dalaran_legion",
}

large_image_instanceMapID = {
    # continents
    -1: "cont_azeroth",
    0: "cont_easternkingdoms",
    1: "cont_kalimdor",
    530: "cont_outland",
    571: "cont_northrend",
    646: "cont_maelstrom",
    730: "cont_maelstrom",
    732: "cont_maelstrom",
    860: "cont_pandaria",
    870: "cont_pandaria",
    1064: "cont_pandaria",
    1116: "cont_draenor",
    1191: "cont_draenor",
    1220: "cont_brokenisles",
    1265: "cont_draenor",
    1464: "cont_draenor",
    1669: "cont_argus",
    # arenas
    562: "arena_bladesedge",
    617: "arena_dalaran",
    559: "arena_nagrand",
    572: "arena_ruinsoflorderan",
    618: "arena_theringofvalor",
    1134: "arena_thetigerspeak",
    980: "arena_tolviron",

    # bgs
    30: "bg_alteracvalley",
    529: "bg_arathibasin",
    1105: "bg_deepwindgeorge",
    566: "bg_eyeofthestorm",
    968: "bg_eyeofthestorm",
    628: "bg_isleofconquest",
    727: "bg_silvershardmine",
    607: "bg_strandoftheancients",
    998: "bg_templeofkotmogu",
    761: "bg_thebattleforgilneas",
    726: "bg_twinpeaks",
    489: "bg_warsonggulch",
    # garrisons
    1152: "garrison_horde",
    1330: "garrison_horde",
    1153: "garrison_horde",
    1154: "garrison_horde",
    1158: "garrison_alliance",
    1331: "garrison_alliance",
    1159: "garrison_alliance",
    1160: "garrison_alliance",
    #  classic dungeons
    48: "exp_classic",  # Blackfathom Deeps",
    230: "exp_classic",  # Blackrock Depths",
    229: "exp_classic",  # Blackrock Spire",
    429: "exp_classic",  # Dire Maul",
    90: "exp_classic",  # Gnomeregan",
    349: "exp_classic",  # Maraudon",
    389: "exp_classic",  # Ragefire Chasm",
    129: "exp_classic",  # Razorfen Downs",
    47: "exp_classic",  # Razorfen Kraul",
    1004: "exp_classic",  # Scarlet Monastery",
    1007: "exp_classic",  # Scholomance",
    33: "exp_classic",  # Shadowfang Keep",
    329: "exp_classic",  # Stratholme",
    36: "exp_classic",  # The Deadmines",
    34: "exp_classic",  # The Stockade",
    109: "exp_classic",  # The Temple of Atal'Hakkar",
    70: "exp_classic",  # Uldaman",
    43: "exp_classic",  # Wailing Caverns",
    209: "exp_classic",  # Zul'Farrak",
    # classic raids
    469: "exp_classic",  # Blackwing Lair",
    409: "exp_classic",  # Molten Core",
    509: "exp_classic",  # Ruins of Ahn'Qiraj",
    531: "exp_classic",  # Temple of Ahn'Qira",
    # burning crusade dungeons
    558: "exp_tbc",  # Auchenai Crypts",
    543: "exp_tbc",  # Hellfire Ramparts",
    585: "exp_tbc",  # Magisters' Terrace",
    557: "exp_tbc",  # Mana-Tombs",
    560: "exp_tbc",  # Old Hillsbrad Foothills",
    556: "exp_tbc",  # Sethekk Halls",
    555: "exp_tbc",  # Shadow Labyrinth",
    552: "exp_tbc",  # The Arcatraz",
    269: "exp_tbc",  # The Black Morass",
    542: "exp_tbc",  # The Blood Furnace",
    553: "exp_tbc",  # The Botanica",
    554: "exp_tbc",  # The Mechanar",
    540: "exp_tbc",  # The Shattered Halls",
    547: "exp_tbc",  # The Slave Pens",
    545: "exp_tbc",  # The Steamvault",
    546: "exp_tbc",  # The Underbog",
    # burning crusade raids
    564: "exp_tbc",  # Black Temple",
    565: "exp_tbc",  # Gruul's Lair",
    534: "exp_tbc",  # Hyjal Summit",
    532: "exp_tbc",  # Karazhan",
    544: "exp_tbc",  # Magtheridon's Lair",
    548: "exp_tbc",  # Serpentshrine Cavern",
    580: "exp_tbc",  # Sunwell Plateau",
    550: "exp_tbc",  # The Eye",
    # wrath dungeons
    619: "exp_wrath",  # Ahn'kahet: The Old Kingdom",
    601: "exp_wrath",  # Azjol-Nerub",
    600: "exp_wrath",  # Drak'Tharon Keep",
    604: "exp_wrath",  # Gundrak",
    602: "exp_wrath",  # Halls of Lightning",
    668: "exp_wrath",  # Halls of Reflection",
    599: "exp_wrath",  # Halls of Stone",
    658: "exp_wrath",  # Pit of Saron",
    595: "exp_wrath",  # The Culling of Stratholme",
    632: "exp_wrath",  # The Forge of Souls",
    576: "exp_wrath",  # The Nexus",
    578: "exp_wrath",  # The Oculus",
    608: "exp_wrath",  # The Violet Hold",
    650: "exp_wrath",  # Trial of the Champion",
    574: "exp_wrath",  # Utgarde Keep",
    575: "exp_wrath",  # Utgarde Pinnacle",
    # wrath raids
    631: "exp_wrath",  # Icecrown Citadel",
    533: "exp_wrath",  # Naxxramas",
    249: "exp_wrath",  # Onyxia's Lair",
    616: "exp_wrath",  # The Eye of Eternity",
    615: "exp_wrath",  # The Obsidian Sanctum",
    724: "exp_wrath",  # The Ruby Sanctum",
    649: "exp_wrath",  # Trial of the Crusader",
    603: "exp_wrath",  # Ulduar",
    624: "exp_wrath",  # Vault of Archavon",
    # cata dungeons
    645: "exp_cata",  # Blackrock Caverns",
    938: "exp_cata",  # End Time",
    670: "exp_cata",  # Grim Batol",
    644: "exp_cata",  # Halls of Origination",
    940: "exp_cata",  # Hour of Twilight",
    755: "exp_cata",  # Lost City of the Tol'vir",
    725: "exp_cata",  # The Stonecore",
    657: "exp_cata",  # The Vortex Pinnacle",
    643: "exp_cata",  # Throne of the Tides",
    939: "exp_cata",  # Well of Eternity",
    568: "exp_cata",  # Zul'Aman",
    859: "exp_cata",  # Zul'Gurub",
    # cata raids
    757: "exp_cata",  # Baradin Hold",
    669: "exp_cata",  # Blackwing Descent",
    967: "exp_cata",  # Dragon Soul",
    720: "exp_cata",  # Firelands",
    671: "exp_cata",  # The Bastion of Twilight",
    754: "exp_cata",  # Throne of the Four Winds",
     # mists dungeons
    962: "exp_mists",  # Gate of the Setting Sun",
    994: "exp_mists",  # Mogu'Shan Palace",
    959: "exp_mists",  # Shado-pan Monastery",
    1011: "exp_mists",  # Siege of Niuzao Temple",
    961: "exp_mists",  # Stormstout Brewery",
    960: "exp_mists",  # Temple of the Jade Serpent",
    # mists raids
    1009: "exp_mists",  # Heart of Fear",
    1008: "exp_mists",  # Mogu'shan Vaults",
    1136: "exp_mists",  # Siege of Orgrimmar",
    996: "exp_mists",  # Terrace of Endless Spring",
    1098: "exp_mists",  # Throne of Thunder",
    # draenor dungeons
    1182: "exp_warlords",  # Auchindoun",
    1175: "exp_warlords",  # Bloodmaul Slag Mines",
    1208: "exp_warlords",  # Grimrail Depot",
    1195: "exp_warlords",  # Iron Docks",
    1176: "exp_warlords",  # Shadowmoon Burial Grounds",
    1209: "exp_warlords",  # Skyreach",
    1279: "exp_warlords",  # The Everbloom",
    1358: "exp_warlords",  # Upper Blackrock Spire",
    # draenor raids
    1228: "exp_warlords",  # Highmaul",
    1205: "exp_warlords",  # Blackrock Foundry",
    1448: "exp_warlords",  # Hellfire Citadel",
    # dungeons
    1501: "dungeon_7_brh",
    1677: "dungeon_7_cath",
    1571: "dungeon_7_cos",
    1466: "dungeon_7_dht",
    1456: "dungeon_7_eoa",
    1477: "dungeon_7_hov",
    1492: "dungeon_7_maw",
    1458: "dungeon_7_nelths",
    1651: "dungeon_7_kara",
    1753: "dungeon_7_seat",
    1516: "dungeon_7_arcway",
    1493: "dungeon_7_vault",
    1544: "dungeon_7_vh",
    # raids
    1520: "raid_7_en",
    1648: "raid_7_tov",
    1530: "raid_7_nh",
    1676: "raid_7_tos",
    1712: "raid_7_abt",
}

large_image_zone = {
    "Trueshot Lodge": "ch_hunter",
    "Acherus: The Ebon Hold": "ch_deathknight",
    "Mardum, the Shattered Abyss": "ch_demonhunter",
    "The Dreamgrove": "ch_druid",
    "Hall of the Guardian": "ch_mage",
    "The Wandering Isle": "ch_monk",
    "Light's Hope Chapel": "ch_paladin",
    "Netherlight Temple": "ch_priest",
    "The Maelstrom": "ch_shaman",
    "Dreadscar Rift": "ch_warlock",
    "Skyhold": "ch_warrior",
    # mini map texts
    "The Hall of Shadows": "ch_rogue",
    "Uncrowned Vault": "ch_rogue",
    "Den of Thieves": "ch_rogue",
}
